# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b066851fdabfde5a8367f55ff4c67d28c5389e0cc41857a510c4e483ad96161f9823f29d9106c978257ba2c1c64e8be8b07696bcde7eeee02e354e930c524479

test:
  secret_key_base: f0ab1afe0d191159c0ec9d6d9869211f91bf8dcfda31fe5f56c6f41144b8661657663f30f8e3fbe65ecb652567d4f7556e53da98f069318a6d459ce28e470668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
